[tool.poetry]
name = "aiesec-mitama"
version = "0.1.0"
description = ""
authors = ["boke0 <speken00.tt@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"
kyokusui = "^0.1.3"

[tool.poetry.dev-dependencies]
mitama = "^4.6.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
